# Generated by Django 4.1.4 on 2023-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='my_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
